//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringConv.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringConv.I18n.GuiStrings", typeof(GuiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly Byte Array 的本地化字符串。
        /// </summary>
        public static string AssemblyByteArray {
            get {
                return ResourceManager.GetString("AssemblyByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assembly String 的本地化字符串。
        /// </summary>
        public static string AssemblyString {
            get {
                return ResourceManager.GetString("AssemblyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C Byte Array 的本地化字符串。
        /// </summary>
        public static string CByteArray {
            get {
                return ResourceManager.GetString("CByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Encoding 的本地化字符串。
        /// </summary>
        public static string CharacterEncoding {
            get {
                return ResourceManager.GetString("CharacterEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Snippets 的本地化字符串。
        /// </summary>
        public static string CodeSnippets {
            get {
                return ResourceManager.GetString("CodeSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Data 的本地化字符串。
        /// </summary>
        public static string CopyData {
            get {
                return ResourceManager.GetString("CopyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C String 的本地化字符串。
        /// </summary>
        public static string CString {
            get {
                return ResourceManager.GetString("CString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Encoding 的本地化字符串。
        /// </summary>
        public static string DataEncoding {
            get {
                return ResourceManager.GetString("DataEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash 的本地化字符串。
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex 的本地化字符串。
        /// </summary>
        public static string Hex {
            get {
                return ResourceManager.GetString("Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex String 的本地化字符串。
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pascal Byte Array 的本地化字符串。
        /// </summary>
        public static string PascalByteArray {
            get {
                return ResourceManager.GetString("PascalByteArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin 的本地化字符串。
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Selected 的本地化字符串。
        /// </summary>
        public static string PinSelected {
            get {
                return ResourceManager.GetString("PinSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Python3 Byte String 的本地化字符串。
        /// </summary>
        public static string Python3ByteString {
            get {
                return ResourceManager.GetString("Python3ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source Url 的本地化字符串。
        /// </summary>
        public static string SourceURL {
            get {
                return ResourceManager.GetString("SourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unicode Escape Sequence 的本地化字符串。
        /// </summary>
        public static string UnicodeEscapeSequence {
            get {
                return ResourceManager.GetString("UnicodeEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL Encoding 的本地化字符串。
        /// </summary>
        public static string UrlEncoding {
            get {
                return ResourceManager.GetString("UrlEncoding", resourceCulture);
            }
        }
    }
}
