//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringConv.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MsgStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StringConv.I18n.MsgStrings", typeof(MsgStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Conversion error: {0} 的本地化字符串。
        /// </summary>
        public static string ConversionError {
            get {
                return ResourceManager.GetString("ConversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All converters cleared. 的本地化字符串。
        /// </summary>
        public static string ConverterCleared {
            get {
                return ResourceManager.GetString("ConverterCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converter fixed: {0} 的本地化字符串。
        /// </summary>
        public static string ConverterFixed {
            get {
                return ResourceManager.GetString("ConverterFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converter removed: {0} 的本地化字符串。
        /// </summary>
        public static string ConverterRemoved {
            get {
                return ResourceManager.GetString("ConverterRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy error: {0} 的本地化字符串。
        /// </summary>
        public static string CopyError {
            get {
                return ResourceManager.GetString("CopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex string must have even length. 的本地化字符串。
        /// </summary>
        public static string HexStringMustHaveEvenLength {
            get {
                return ResourceManager.GetString("HexStringMustHaveEvenLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text copied to clipboard. 的本地化字符串。
        /// </summary>
        public static string TextCopied {
            get {
                return ResourceManager.GetString("TextCopied", resourceCulture);
            }
        }
    }
}
